version: "3.8"

services:
  # 1. BACKEND API SERVICE (Bản đơn giản)
  backend:
    build: ./backend
    container_name: p2p_backend_level1
    ports:
      # Ở Level 1, backend được public trực tiếp
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    networks:
      - app-network

  # 2. FRONTEND SERVICE (Bản đơn giản)
  frontend:
    build: ./frontend
    container_name: p2p_frontend_level1
    ports:
      # Frontend cũng được public trực tiếp
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      # >>> LƯU Ý: Frontend cần biết API đang ở port 5000 <<<
      - REACT_APP_API_URL=http://localhost:5000/api
      - NODE_OPTIONS=--openssl-legacy-provider
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    networks:
      - app-network

  # 3. DATABASE SERVICE
  mongodb:
    image: mongo:latest
    container_name: p2p_mongodb_level1
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local